server:
  port: 8800
spring:
  profiles:
    active: ${JJCHE_WEB_PROFILES_ACTIVE:dev}
  application:
    name: "@project.artifactId@"
  boot:
    admin:
      ui:
        external-views:
  cloud:
    #配置Bus id(远程推送事件)
    bus:
      id: ${spring.application.name}:${server.port}
    nacos:
      discovery:
        namespace: ${JJCHE_NACOS_NAMESPACE:}
        server-addr: ${JJCHE_NACOS_HOST:127.0.0.1}:${JJCHE_NACOS_PORT:8848}
        metadata:
          management.context-path: ${management.endpoints.web.base-path}
      config:
        namespace: ${spring.cloud.nacos.discovery.namespace}
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 配置对应的分组
        group: DEFAULT_GROUP
        # 配置文件后缀
        file-extension: yml
logging:
  file:
    path: ${JJCHE_LOG_PATH:./logs}
    name: all.log