JAVA_OPTS=""
JAVA_WEB_SERVICE_OPTS=""

#mysql
export BOOT_ADMIN_DB_HOST=""
export BOOT_ADMIN_DB_DATABASE=""
export BOOT_ADMIN_DB_UNAME=""
export BOOT_ADMIN_DB_PASSWORD=""
export BOOT_ADMIN_DB_PORT="36010"

#redis
export BOOT_ADMIN_REDIS_DB=""
export BOOT_ADMIN_REDIS_HOST=""
export BOOT_ADMIN_REDIS_PORT=""
export BOOT_ADMIN_REDIS_PASSWORD="16379"

#sba
export BOOT_ADMIN_SBA_PASSWORD=""

#user
export BOOT_ADMIN_USER_PASSWORD_DEFAULT-VAL=""

#filter
BOOT_ADMIN_FILTER_ENCRYPTION_FIELD_SECRET=""

#jwt
export BOOT_ADMIN_SECURITY_JWT_BASE64-SECRET=""