server:
  port: 8801
spring:
  redis:
    database: ${JJCHE_REDIS_DB:1}
    host: ${JJCHE_REDIS_HOST:localhost}
    port: ${JJCHE_REDIS_PORT:6379}
    password: ${JJCHE_REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 1
  profiles:
    active: ${JJCHE_WEB_PROFILES_ACTIVE:dev}
  application:
    name: jjche-cloud-gateway
  cloud:
    nacos:
      discovery:
        namespace: ${JJCHE_NACOS_NAMESPACE:}
        server-addr: ${JJCHE_NACOS_HOST:127.0.0.1}:${JJCHE_NACOS_PORT:8848}
        metadata:
          version: ${spring.profiles.active}
      route:
        config:
          data-id: jjche-cloud-gateway-router
          group: DEFAULT_GROUP
          #自定义路由配置 yml nacos database
          data-type: nacos
    gateway:
      enabled: true
      api-prefix: /api
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: false
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    #Sentinel配置
    sentinel:
      transport:
        dashboard: ${JJCHE_SENTINEL_HOST:127.0.0.1}:${JJCHE_SENTINEL_PORT:8900}
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false