spring:
  data:
    redis:
      repositories:
        enabled: false

jjche:
  liquibase:
    change-log: classpath:liquibase/changelog/master.xml
  user:
    account:
      expired-days: 90
    password:
      default-val: ${JJCHE_USER_PASSWORD_DEFAULT_VAL:123456}
      new-user-must-reset: true
      min-length: 8
      max-length: 20
      upper-case: true
      lower-case: true
      digit: true
      special-char: true
      fails-max-count: 5
      advance-day-must-reset: 1
      advance-day-tip-reset: 15
      expired-days: 90
  task:
    pool:
      # 核心线程池大小
      core-pool-size: 10
      # 最大线程数
      max-pool-size: 30
      # 活跃时间
      keep-alive-seconds: 60
      # 队列容量
      queue-capacity: 50
aj:
  captcha:
    cache-type: redis
    water-mark: jjche-boot
    aes-status: true